### ISSUE TITLE
GPG check failed

### ISSUE THREAD

**Issue by tim427** [negativo17/sonarr#2]
```Package sonarr-3.0.7.1477-1.el8.noarch.rpm is not signed
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: GPG check FAILED```

Just a heads up; latest version isn't signed (yet)!

**Comment by scaronni** [comment]
Which branch is this? Fedora 34, 35, EL8?

**Comment by tim427** [comment]
> Which branch is this? Fedora 34, 35, EL8?
My bad, forgot to mention: EL8 :)

**Comment by scaronni** [comment]
I have some hard drive issues, any intensive I/O is failing, I guess I need to recheck the signature of all packages.

**Comment by scaronni** [comment]
Coming online in a few minutes, I had to remove an apparently good disk from an array :/

**Comment by scaronni** [comment]
Coming online in a few minutes, I had to remove an apparently good disk from an array :/
